name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - python=3.14
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - pathlib
  - numpy
  - matplotlib
  - rasterio
  - rioxarray
  - xarray
  - xarray-spatial
  - geopandas
  - scipy
  - shapely
  - jupytergis
# packages to aid in cookbook development
  - jupyterlab-git
  - jupyter-server-proxy
  - vim
